name: Terraform EC2 Deployment

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
         
          docker build -t mynginx .
         
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         
          docker tag mynginx $DOCKER_USERNAME/mynginx
          
          docker push $DOCKER_USERNAME/mynginx

      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-2

      - name: SSH into EC2 instance and deploy container
        uses: appleboy/ssh-action@master
        with:
          host: "3.87.184.71"
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull "${{ secrets.DOCKER_USERNAME }}/mynginximage:latest"
            docker run -d --restart=always -p 80:80 "${{ secrets.DOCKER_USERNAME }}/mynginximage:latest"
